"""Smoke tests for sdk/python/spl/crypto.py (auto-generated by pact adopt)."""

import pytest

def test_import_sdk_python_spl_crypto():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.crypto")
    assert mod is not None

def test_sha256_is_callable():
    """Function sha256 exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.crypto")
    fn = getattr(mod, "sha256", None)
    assert fn is not None, "'sha256' not found in sdk.python.spl.crypto"
    assert callable(fn)

def test_sha256_hex_is_callable():
    """Function sha256_hex exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.crypto")
    fn = getattr(mod, "sha256_hex", None)
    assert fn is not None, "'sha256_hex' not found in sdk.python.spl.crypto"
    assert callable(fn)

def test_verify_ed25519_is_callable():
    """Function verify_ed25519 exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.crypto")
    fn = getattr(mod, "verify_ed25519", None)
    assert fn is not None, "'verify_ed25519' not found in sdk.python.spl.crypto"
    assert callable(fn)

def test_verify_merkle_proof_is_callable():
    """Function verify_merkle_proof exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.crypto")
    fn = getattr(mod, "verify_merkle_proof", None)
    assert fn is not None, "'verify_merkle_proof' not found in sdk.python.spl.crypto"
    assert callable(fn)

def test_hash_tuple_is_callable():
    """Function hash_tuple exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.crypto")
    fn = getattr(mod, "hash_tuple", None)
    assert fn is not None, "'hash_tuple' not found in sdk.python.spl.crypto"
    assert callable(fn)

def test_derive_service_key_is_callable():
    """Function derive_service_key exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.crypto")
    fn = getattr(mod, "derive_service_key", None)
    assert fn is not None, "'derive_service_key' not found in sdk.python.spl.crypto"
    assert callable(fn)

def test_verify_hash_chain_is_callable():
    """Function verify_hash_chain exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.crypto")
    fn = getattr(mod, "verify_hash_chain", None)
    assert fn is not None, "'verify_hash_chain' not found in sdk.python.spl.crypto"
    assert callable(fn)
