"""Smoke tests for sdk/python/spl/token.py (auto-generated by pact adopt)."""

import pytest

def test_import_sdk_python_spl_token():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.token")
    assert mod is not None

def test_generate_keypair_is_callable():
    """Function generate_keypair exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.token")
    fn = getattr(mod, "generate_keypair", None)
    assert fn is not None, "'generate_keypair' not found in sdk.python.spl.token"
    assert callable(fn)

def test_signing_payload_is_callable():
    """Function signing_payload exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.token")
    fn = getattr(mod, "signing_payload", None)
    assert fn is not None, "'signing_payload' not found in sdk.python.spl.token"
    assert callable(fn)

def test_create_presentation_signature_is_callable():
    """Function create_presentation_signature exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.token")
    fn = getattr(mod, "create_presentation_signature", None)
    assert fn is not None, "'create_presentation_signature' not found in sdk.python.spl.token"
    assert callable(fn)

def test_mint_is_callable():
    """Function mint exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.token")
    fn = getattr(mod, "mint", None)
    assert fn is not None, "'mint' not found in sdk.python.spl.token"
    assert callable(fn)

def test_verify_token_is_callable():
    """Function verify_token exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.token")
    fn = getattr(mod, "verify_token", None)
    assert fn is not None, "'verify_token' not found in sdk.python.spl.token"
    assert callable(fn)
