"""Smoke tests for sdk/python/spl/evaluator.py (auto-generated by pact adopt)."""

import pytest

def test_import_sdk_python_spl_evaluator():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.evaluator")
    assert mod is not None

def test_eval_policy_is_callable():
    """Function eval_policy exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.evaluator")
    fn = getattr(mod, "eval_policy", None)
    assert fn is not None, "'eval_policy' not found in sdk.python.spl.evaluator"
    assert callable(fn)
