"""Smoke tests for sdk/python/spl/parser.py (auto-generated by pact adopt)."""

import pytest

def test_import_sdk_python_spl_parser():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.parser")
    assert mod is not None

def test_tokenize_is_callable():
    """Function tokenize exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.parser")
    fn = getattr(mod, "tokenize", None)
    assert fn is not None, "'tokenize' not found in sdk.python.spl.parser"
    assert callable(fn)

def test_parse_is_callable():
    """Function parse exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.parser")
    fn = getattr(mod, "parse", None)
    assert fn is not None, "'parse' not found in sdk.python.spl.parser"
    assert callable(fn)
