"""Smoke tests for sdk/python/spl/__main__.py (auto-generated by pact adopt)."""

import pytest

def test_import_sdk_python_spl___main__():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.__main__")
    assert mod is not None

def test_main_is_callable():
    """Function main exists and is callable."""
    import importlib
    mod = importlib.import_module("sdk.python.spl.__main__")
    fn = getattr(mod, "main", None)
    assert fn is not None, "'main' not found in sdk.python.spl.__main__"
    assert callable(fn)
